### ISSUE TITLE
miner fees system tests using implicit fees

### ISSUE THREAD

**Issue by stewartie4** [0chain/system_test#107]
- work with devops to configure the CI chain to charge miner fees via helm
- register the fee amount in test config so the tests can still run against a chain that charges 0 fees
- add explicit tests that assert wallet has been charged this fee for transactions that require miner input as per https://0chain.slack.com/archives/C026YA5EYH3/p1635353099047800?thread_ts=1635175118.028000&cid=C026YA5EYH3
- ensure transactions that are excempt for fees are NOT charged: https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/transaction/entity.go#L91
- chat to devops(eg. Anish/Mohd) to enable fees on all chains by default
- Also fix === SKIP: tests/cli_tests TestMinerFeesPayment (0.00s)

**Comment by stewartie4** [comment]
re-opening because the majority of tests have not been written due to bugs

**Comment by Kishan-Dhakan** [comment]
Merged with https://github.com/0chain/system_test/issues/467
