### ISSUE TITLE
free storage tests

### ISSUE THREAD

**Issue by stewartie4** [0chain/system_test#114]
Investigate and Implement system acceptance tests that test the free storage functionality
- max number of free storage tokens per year
  
Following the[ test style guide](https://docs.google.com/document/d/12RtuT89FG7PycsOno7312yQoJ4nzzfs0xLBEDA38Q5k/edit?usp=sharing) and the style of the existing tests

**Comment by moldis** [comment]
@stewartie4 Open question here, as we need to deploy chain with owners wallet.

**Comment by stewartie4** [comment]
@moldis we should be able to hardcode the owner - @avanaur has done similar for the sc modification tests

**Comment by avanaur** [comment]
https://github.com/0chain/zboxcli#free-storage-allocation
