### ISSUE TITLE
repair allocation system tests

### ISSUE THREAD

**Issue by stewartie4** [0chain/system_test#117]
Investigate and Implement system acceptance tests that test allocation repair functionality 
Example test cases are below but **this is not a complete list.**
Also create your own, thinking about security, param validation, error messaging, performance etc.

attempt file repair on single file that needs repaired 
attempt file repair on multiple files that needs repaired 
attempt file repair on file that does need repaired with a file that does not need repaired
attempt file repair on file that does not exist
attempt file repair using local path that does not exist
don't supply repair path
don't supply root path

Repair by delete
Repair by upload

a system test where we replace all blobbers with new ones with no data loss

Following the[ test style guide](https://docs.google.com/document/d/12RtuT89FG7PycsOno7312yQoJ4nzzfs0xLBEDA38Q5k/edit?usp=sharing) and the style of the existing tests

**Comment by dabasov** [comment]
there is no reason to make repair in cli, it will be done automatically in gosdk during normal functionality. we will test it in conductor tests other than [#731](https://github.com/0chain/system_test/pull/731)
