### ISSUE TITLE
Update global config system tests

### ISSUE THREAD

**Issue by stewartie4** [0chain/system_test#131]
Investigate and Implement system acceptance tests that updates global chain config

Example test cases are below but this is not a complete list.
Also create your own, thinking about security, param validation, error messaging, performance  etc.

./zwallet global-config
./zwallet global-update-config
- Retrieve chain config
- Update chain config specifying key/value
- Retrieve chain config again ensuring the value is updated
- Update with invalid config 
- Update key that does not exist
- Supply no params

Following the [test style guide](https://docs.google.com/document/d/12RtuT89FG7PycsOno7312yQoJ4nzzfs0xLBEDA38Q5k/edit) and the style of the existing tests

**Comment by dabasov** [comment]
there is an issue I've fixed regarding the owner [issue432]( https://github.com/0chain/0chain/issues/432)
The idea is simple: move owner out of the code and make it configurable through 0chain.yaml and zwallet.
This section is added to several contracts:
`` minersc:
            ownerId: 1746b06bb09f55ee01b33b5e2e055d6cc7a900cb57c0a3a5eaabb8a0e7745802
``
Owner can change itself to another address that will become the new owner.
Only owner can change configs, minersc owner can change globals.

So, we need to test that after change old owner won't be able to change globals and only the new one will

**Comment by stewartie4** [comment]
@mohsenno1 this PR may help https://github.com/0chain/0chain/pull/501/files
