### ISSUE TITLE
Add test cases for API endpoint `/v1/block/get/latest_finalized_magic_block` 

### ISSUE THREAD

**Issue by peterlimg** [0chain/system_test#139]
We added one param `node-lfmb-hash` to this API endpoint, so please add test cases to cover the changes. 

Expected behaviors:
- If there's no param provided, return the whole lfmb message as before
- `node-lfmb-hash` is provided, but is different from the current lfmb, return the lfmb the sharder has
- `node-lfmb-hash` is provided and it's the same as the sharder's, return `304 Not modified` status code only.

**Comment by stewartie4** [comment]
Hey @peterlimg we'll add the tests once we start writing more detailed API tests but normally when a new feature is written it needs to be the dev that wrote the change or someone else with context writing the test as we don't have capacity to test every new feature merging in these days - we'd never keep up 😆

**Comment by peterlimg** [comment]
Cool, I'll try to add the tests
