### ISSUE TITLE
Blobber challenge system tests

### ISSUE THREAD

**Issue by stewartie4** [0chain/system_test#160]
Investigate and Implement system acceptance tests that tests blobber challenge functionality 

Challenge should be created for all CRUD actions if there is data - 
upload, 
update, 
delete, 
move, 
copy, 
rename, 
download.

See this comment for more info on the challenge process https://github.com/0chain/0chain/issues/741#issuecomment-1008002060

Forcing challenges should be possible by CRUD on a file > 1MB using the generate_challenges endpoint
https://0chain.slack.com/archives/G01FYNN6DK4/p1642510909050000?thread_ts=1642425835.040800&cid=G01FYNN6DK4

**Comment by Kishan-Dhakan** [comment]
As Per reading the mentioned comment, I noted the following cases should be covered (from a UAT perspective):
- Upload:
  - Total data stored on blobber increases by file size
  - Allocation is added to blobber's allocation partition if allocation's used size is over 1 MB

- Delete:
  - Total data stored on blobber decreases by deleted file size 
  - Allocation is removed from blobber's allocation partition if allocation's used size is below 1 MB

- Download:
  - Doesn't really have a challenge case

- Challenge:
  - Challenge creation verification (for files in allocation)
  - Challenge response verification

If there's anymore let me know🙌

**Comment by stewartie4** [comment]
@guruhubb any additional coverage you think would be useful here re: challenges?
