### ISSUE TITLE
Deploy authoriser service along with 0chain

### ISSUE THREAD

**Issue by Dmdv** [0chain/system_test#161]
Authorizer token bridge CI/CD:

https://github.com/0chain/token_bridge_authserver/blob/staging/.github/workflows/build-%26-publish-docker-image.yml

The current system-tests implementation has custom miner and sharder instances.
However for ZCNSC bridge we also need a set of minimum 3 authorizers deployed with the 0chain.

**Comment by anish-squareops** [comment]
@Dmdv Added code and configs to deploy 3 authorizers with every network in system tests.

**Comment by anish-squareops** [comment]
<img width="960" alt="Screenshot 2022-01-11 172440" src="https://user-images.githubusercontent.com/68534207/148938288-28e9520d-b94b-4914-99ad-30d8403cddde.png">

**Comment by stewartie4** [comment]
Thanks @anish-squareops 
I have raised the following PRs to allow the authorizer branch to be specified and fit in with the CI standards and to enable auto image publish on staging in authorizer repo
https://github.com/0chain/actions/pull/13
https://github.com/0chain/0chain/pull/873
https://github.com/0chain/token_bridge_authserver/pull/8/files

**Comment by Dmdv** [comment]
> <img alt="Screenshot 2022-01-11 172440" width="960" src="https://user-images.githubusercontent.com/68534207/148938288-28e9520d-b94b-4914-99ad-30d8403cddde.png">

```
{"error":"eventsDB not initialized"}
```

https://dev-2.devnet-0chain.net/miner01/v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712e0/getAuthorizerNodes

**Comment by Dmdv** [comment]
After recent update 

3 calls of `AddAuthorizer` methods

https://dev-2.devnet-0chain.net/miner01/v1/scstats/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712e0


but no Authorizers

```
{"error":"authorizerID is empty"}
```

**Comment by Dmdv** [comment]
Fixed
