### ISSUE TITLE
Increase directory test coverage

### ISSUE THREAD

**Issue by stewartie4** [0chain/system_test#180]
Increase coverage around directories:

- [ ] move, copy, delete root directory
- [ ] move, copy, delete nested directory
- [ ] move, copy, delete directory with no files
- [ ] move, copy, delete directory with multiple files
- [ ] share a directory -- Already covered (Share to public a folder with no encrypted file using auth ticket): add more cases: encrypted, unencrypted, public, private, with and without files
- [ ] rename directory

**Comment by Kishan-Dhakan** [comment]
https://github.com/0chain/system_test/pull/834
