### ISSUE TITLE
Add/replace blobber system tests

### ISSUE THREAD

**Issue by Kishan-Dhakan** [0chain/system_test#252]
Adding or replacing a blobber should be supported for allocations. The following scenarios (not an exhaustive list, please think of other cases which need coverage, security, etc. when you pick up this task) need to be tested:

- Adding a blobber as additional Parity shard should work
- Adding a blobber as additional Data shard should work
- Replacing a blobber that held data shards should work
- Replacing a blobber that held parity shards should work
- Token accounting (read pool, write pool, etc.) for added or replacement blobber

**Comment by YarikRevich** [comment]
- Adding a blobber as additional Data shard should work
- Replacing a blobber that held data shards should work
- Replacing a blobber that held parity shards should work
Are blacklist techniques. @dabasov can confirm that
