### ISSUE TITLE
Investigate and resolve skipped tests

### ISSUE THREAD

**Issue by stewartie4** [0chain/system_test#284]
There are currently 30+ skipped tests.
Investigate which of these tests skipped skipped and why. The hope is that any instability in the past may have been resolved and with events DB we can now run them

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/18306778/171068264-9be7be8b-ddea-4d6b-8adb-73a5e6b26ab2.png">

Also investigate blobber accounting broken scenarios which should be working now

Acceptance criteria:
- for the 30 skipped tests and blobber accounting scenarios: 
- Sync with blockchain devs and attempt to enable the skipped test, updating as necessary 
- If test cannot be enabled, raise an issue and log the reason in the skip message and test name, or delete the test (tests should not be skipped long term)

**Comment by Hassaan008** [comment]
It has been divided into smaller tickets for each of the skipped tests.

**Comment by stewartie4** [comment]
@Hassaan008 could you link them all here please and i'll add them to the board? Otherwise they're hard to track
Thanks

**Comment by Hassaan008** [comment]
- [ ] https://github.com/0chain/system_test/issues/344
- [ ] https://github.com/0chain/system_test/issues/345
- [ ] https://github.com/0chain/system_test/issues/352
- [ ] https://github.com/0chain/system_test/issues/354
- [ ] https://github.com/0chain/system_test/issues/355
- [ ] https://github.com/0chain/system_test/issues/357
- [ ] https://github.com/0chain/system_test/issues/358
- [ ] https://github.com/0chain/system_test/issues/359
- [ ] https://github.com/0chain/system_test/issues/360
- [ ] https://github.com/0chain/system_test/issues/362
- [ ] https://github.com/0chain/system_test/issues/363
