### ISSUE TITLE
Collect-rewards for Validators

### ISSUE THREAD

**Issue by Kishan-Dhakan** [0chain/system_test#305]
- Test Collect rewards functionality for Validators (once `ls-validators` is added to zbox)
- Reference PR: https://github.com/0chain/system_test/pull/287

**Comment by Kishan-Dhakan** [comment]
Related PRs: https://github.com/0chain/zboxcli/pull/253
cc @Shrhawk

**Comment by Shrhawk** [comment]
This is on hold, till the required changes are done to collect rewards for validator
