### ISSUE TITLE
System tests review and tidy up

### ISSUE THREAD

**Issue by stewartie4** [0chain/system_test#32]
- consider better regex for USD -  [0-9]*[.])?[0-9]+ https://github.com/0chain/system_test/pull/28#discussion_r711050338
- add strings.join(output "\n") to require.Equal tests or change to require.Len(t, output, 0) 
- strip out blank and duplicate lines from command output
- remove boilerplate code from tests https://0chain.slack.com/archives/C02AV6MKT36/p1635274843078900?thread_ts=1635272798.078200&cid=C02AV6MKT36
- remove duplicated utility methods from tests https://0chain.slack.com/archives/C02AV6MKT36/p1635272798078200
- add additional calls to verify operations rather than just relying on cli exit status and message eg. list files after an upload, etc.
- add polling instead of explicit waits

**Comment by Kishan-Dhakan** [comment]
Closing this as a stale issue.
