### ISSUE TITLE
Integrate subset of conductor tests to CI pipeline

### ISSUE THREAD

**Issue by stewartie4** [0chain/system_test#327]
As per https://0chain.slack.com/archives/C01GMABG2T1/p1657523593451969 we need a way to periodically restart miners and shaders on a running network to test resiliency.
[Conductor tests ](https://github.com/0chain/0chain/tree/staging/code/go/0chain.net/conductor) have the ability to test this but we need to be able to run a small subset of these on the pipeline so they don't take hours to run.

Sync with devops and create a small subset of useful conductor tests (restarting miners/sharders and other tests) and get these smoke tests to run as part of the CI pipeline

**Comment by Jayashsatolia403** [comment]
Conductor tests are added to 0chain already.
