### ISSUE TITLE
Blobber: /v1/file/referencepath & objecttree API tests and doc review

### ISSUE THREAD

**Issue by stewartie4** [0chain/system_test#338]
Investigate and Implement system acceptance tests directly against the blobber  /v1/file/objectpath  /v1/file/referencepath and objecttree APIs
Example test cases for each endpoint are below but **this is not a complete list.**
Also create your own, thinking about security, param validation, error messaging, performance etc.

valid request(s)
no allocation id
invalid allocation id
someone else's allocation
invalid owner
no paths
null paths
invalid path
expired allocation
invalid signature 
empty body/params/form
  
Following the[ test style guide](https://docs.google.com/document/d/12RtuT89FG7PycsOno7312yQoJ4nzzfs0xLBEDA38Q5k/edit?usp=sharing) and the style of the existing API tests

Also check that this endpoint is list on api.0chain.net and is up to date with a recent example

**Comment by Kishan-Dhakan** [comment]
/GetObjectPath API is removed as from blobbers in https://github.com/0chain/blobber/pull/863.
