### ISSUE TITLE
fix skipped ZCN bridge tests

### ISSUE THREAD

**Issue by ssardana08** [0chain/system_test#360]
=== SKIP: tests/cli_tests TestBurnTicket/Get_WZCN_burn_ticket (0.00s)
=== SKIP: tests/cli_tests TestBurnTicket/Get_ZCN_burn_ticket (0.00s)
=== SKIP: tests/cli_tests TestBridgeMint/Mint_ZCN_tokens (0.00s)
=== SKIP: tests/cli_tests TestBridgeMint/Mint_WZCN_tokens (0.00s)
=== SKIP: tests/cli_tests TestBridgeBurn/Burning_ZCN_tokens (0.00s)
=== SKIP: tests/cli_tests TestBridgeBurn/Burning_WZCN_tokens (0.00s)
=== SKIP: tests/cli_tests TestZCNBridgeGlobalSettings (0.00s)
=== SKIP: tests/cli_tests TestBridgeVerify/Verify_ethereum_transaction (0.00s)

Point of contact: @YarikRevich 

New coverage: Add fee tests for authorizers (blocked by development as of now)

**Comment by Kishan-Dhakan** [comment]
Closed by #481
