### ISSUE TITLE
Fix system test for NFT allocation features

### ISSUE THREAD

**Issue by lawRathod** [0chain/system_test#398]
New features for allocation added in the PR: 
* https://github.com/0chain/0chain/pull/1453/files
Fix system tests accordingly. Other new tests will be added within another issue.
Features list:
* https://github.com/0chain/0chain/issues/828

**Comment by devyetii** [comment]
Scenarios:
1. `newallocation` zboxcli input should affect the created allocation
    1. Default values of new fields of the created allocation 
    2. `--set-third-party-extendable`
    3. `--forbid_*`
    4. Combination of file_options give correct mask 
2. `updateallocation` zboxcli input should affect the created allocation
    1. `--set-third-party-extendable`
    2. `--forbid_*`
    3. `--allow_*`
    4. Combination of file_options give correct mask
3. Immutable allocation shouldn't be set back to mutable, as well as the third-party-extendable.
5. Third-party extendability
    1. `third_party_extendable = false` => Can only be updated by the owner
    2. `third_party_extendable = true`  => Only size/expiration can be **INCREASED** by others
6. File options
    1. Upload (Allow/Forbid)
    2. Move (Allow/Forbid)
    3. Update (Allow/Forbid)
    5. Delete (Allow/Forbid)
    6. Copy (Allow/Forbid)
    7. Rename (Allow/Forbid)

**Comment by devyetii** [comment]
New system tests for the changes will be in #529
