### ISSUE TITLE
Multiple stake pool test does not do what it says. Change test name or test.

### ISSUE THREAD

**Issue by Sriep** [0chain/system_test#489]
"Multiple stakes against a miner should create multiple pools"
The test does not do this. We should either change the test name or the test.

A while ago, we changed stake pools, so there is only one stake pool per user.

This test adds 1 token to the same stake pool twice, then checks it is two. 

To perform the described test we would want two different users to lock tokens in a stake pool. Then check we have two stake pools.

**Comment by stewartie4** [comment]
closed by https://github.com/0chain/system_test/pull/490
