### ISSUE TITLE
OBox: NFT collections system tests

### ISSUE THREAD

**Issue by stewartie4** [0chain/system_test#511]
Implement system acceptance tests for 0box that test the NFT collections functionality.
example (but not exhaustive) test cases.

**POST collection**
`/v2/nft/collection [post]`
Valid request
Invalid requests (as many as you can think of: missing fields, invalid fields etc.)
**Get collection**
`/v2/nft/collection [get]`
Valid request
Invalid requests (as many as you can think of: missing fields, invalid fields etc.)
**Get all collections**
`/v2/nft/collections [get]`
Valid request 
Invalid requests (as many as you can think of: missing fields, invalid fields etc.)
**Update collection**
`/v2/nft/collection [put]`
Valid request
Invalid requests (as many as you can think of: missing fields, invalid fields etc.)

- Security on all the above endpoints eg. list, update another wallet's collection etc.

See the 0box postman collection for endpoints:
https://github.com/0chain/0box/blob/staging/e2e/0chain-0box.postman_collection.json

[Following the test style guide](https://docs.google.com/document/d/12RtuT89FG7PycsOno7312yQoJ4nzzfs0xLBEDA38Q5k/edit?usp=sharing) and the style of the existing 0box tests

**Comment by Kishan-Dhakan** [comment]
Closed by #575
