### ISSUE TITLE
0Box: NFT State/Info system tests

### ISSUE THREAD

**Issue by stewartie4** [0chain/system_test#513]
Implement system acceptance tests for 0box that test the NFT state and info functionality.
example (but not exhaustive) test cases.

POST NFT info
- Valid request
- Invalid requests (as many as you can think of: missing fields, invalid fields etc.)
PUT NFT info 
- Valid request
- Invalid requests (as many as you can think of: missing fields, invalid fields etc.)
PUT NFT state
- Valid request 
- Invalid requests (as many as you can think of:  missing fields, invalid fields etc.)
GET NFT state
- Valid request 
- Invalid requests (as many as you can think of:  missing fields, invalid fields etc.)

See the 0box postman collection for endpoints:
https://github.com/0chain/0box/blob/staging/e2e/0chain-0box.postman_collection.json 

[Following the test style guide](https://docs.google.com/document/d/12RtuT89FG7PycsOno7312yQoJ4nzzfs0xLBEDA38Q5k/edit?usp=sharing) and the style of the existing 0box tests

**Comment by Manali-Jain-squareops** [comment]
https://github.com/0chain/system_test/pull/518

**Comment by Kishan-Dhakan** [comment]
This endpoint has been removed.
