### ISSUE TITLE
0Box: Test coverage review

### ISSUE THREAD

**Issue by stewartie4** [0chain/system_test#548]
Review test coverage written under the following issues:
https://github.com/0chain/system_test/issues/499
https://github.com/0chain/system_test/issues/508
https://github.com/0chain/system_test/issues/511
https://github.com/0chain/system_test/issues/512
https://github.com/0chain/system_test/issues/513
https://github.com/0chain/system_test/issues/515
https://github.com/0chain/system_test/issues/521
https://github.com/0chain/system_test/issues/522
https://github.com/0chain/system_test/issues/523
https://github.com/0chain/system_test/issues/547

Compare it with the codebase and postman collection
https://github.com/0chain/0box/blob/staging/e2e/0chain-0box.postman_collection.json
ensuring that:

1. All endpoints are covered
2. The depth of coverage is good, eg. error scenarios, field validation, edge cases etc.
3. Style, naming and test efficiency meets standards 

Improve as necessary

**Comment by Kishan-Dhakan** [comment]
Closed as coverage review has been added to this sheet: https://docs.google.com/spreadsheets/d/1_vvJc7DedDMseBOjzbJUOdL-jBRcnSJ97jH_DvTp-xc/edit#gid=1109891884. cc @stewartie4
