### ISSUE TITLE
Increase system test miners to eleven and sharders to three.

### ISSUE THREAD

**Issue by Sriep** [0chain/system_test#582]
We need to increase the number of miners in system tests to eleven and sharders to three. This will require changes to the [actions](https://github.com/0chain/actions) project.

https://docs.google.com/spreadsheets/d/1_vvJc7DedDMseBOjzbJUOdL-jBRcnSJ97jH_DvTp-xc/edit#gid=104708095

**Comment by Kishan-Dhakan** [comment]
Closed by @m-s-a-c
