### ISSUE TITLE
Transfer allocation system tests

### ISSUE THREAD

**Issue by stewartie4** [0chain/system_test#61]
Implement system acceptance tests that test the allocation transfer functionality

Example test cases are below but this is not a complete list.
Also create your own, thinking about security, param validation, error messaging, performance  etc.

- transfer empty allocation - what happens to tokens in the old owner's wallet/write pool, what happens to tokens in the new owner's wallet/write pool
- transfer allocation with encrypted file - can the encrypted file still be used by the new owner
- transfer allocation with non encrypted file - can the encrypted file still be used by the new owner
- transfer allocation - allocation cannot be used by previous owner 
- transfer allocation - what happens to files shared/auth tickets issued by the previous owner?
- transfer allocation - what happens to collaborators added by the previous owner?
- transfer allocation - what happens to curators added by the previous owner?
- transfer with invalid wallet id
- transfer with invalid public key
- transfer to yourself
- transfer expired allocation
- transfer finalized an allocation 
- transfer non-existent allocation
- the usual params checks : -1 as a value, required param not supplied etc.

- token accounting - how does a transfer of an allocation affect the pools of the blobbers (if at all) and the wallet of the old owner and the wallet of the new owner? - does the old owner get their tokens back?

[Following the test style guide](https://docs.google.com/document/d/12RtuT89FG7PycsOno7312yQoJ4nzzfs0xLBEDA38Q5k/edit?usp=sharing) and the style of the existing tests

**Comment by Sriep** [comment]
The owner now has the option to transfer allocation ownership, https://github.com/0chain/0chain/pull/604.
