### ISSUE TITLE
Cypress: Scoping

### ISSUE THREAD

**Issue by stewartie4** [0chain/system_test#694]
A lot of time is spent on manual validation and re-validation.
Cypress/Selenium automated UI tests help with this, but coverage is low right now.

Scope out existing cypress tests:
- Breadth and depth of existing tests per app
- CI integration
- Time and resources 

End result should be a test plan for expanding the existing cypress suite.

**Comment by stewartie4** [comment]
Cypress put on hold until initial dev work is complete

**Comment by Kishan-Dhakan** [comment]
Closing as inital cypress tests are added now to each webapp. We can branch this ticket going forward to increase coverage.
