### ISSUE TITLE
disable non migration tests in s3migration repo

### ISSUE THREAD

**Issue by boddumanohar** [0chain/system_test#737]
https://github.com/0chain/s3-migration/blob/staging/.github/workflows/system_tests.yaml

https://0chain.slack.com/archives/C02AV6MKT36/p1687734207717949?thread_ts=1687728243.727799&cid=C02AV6MKT36

**Comment by Kishan-Dhakan** [comment]
Closed by https://github.com/0chain/actions/pull/229, https://github.com/0chain/system_test/pull/793 and https://github.com/0chain/s3-migration/pull/84.
