### ISSUE TITLE
Update file system tests

### ISSUE THREAD

**Issue by stewartie4** [0chain/system_test#74]
Investigate and Implement system acceptance tests that test file update functionality 

Example test cases are below but this is not a complete list.
Also create your own, thinking about security, param validation, error messaging, performance  etc.

- Update existing file
- Update with thumbnail 
-  Update with commit 

- Update existing file in another allocation
- Update file to be larger than the allocation allows
- Update file that does not exist
- Update non-encrypted file with encrypted file 
- Update encrypted file with encrypted file 
- Update encrypted file with non-encrypted file 
- Update only thumbnail
- Update directory 

- token accounting: https://drive.google.com/file/d/1tNjb_OvX93s47QQ2gFrfeUBdmP0PcL9k/view will be an invaluable resource, also chat to the blockchain devs

Following the [test style guide](https://docs.google.com/document/d/12RtuT89FG7PycsOno7312yQoJ4nzzfs0xLBEDA38Q5k/edit) and the style of the existing tests

**Comment by littlestar642** [comment]
Hey @stewartie4 

Isnt updating directory test case something that we can achieve with `./zbox move` command. 

What are your expectations with writing this in update file test?

**Comment by stewartie4** [comment]
@littlestar642 yeah rename the directory or update it's path my moving
