### ISSUE TITLE
Investigate /v2/graph-total-locked flakiness & zs3server test

### ISSUE THREAD

**Issue by Kishan-Dhakan** [0chain/system_test#773]
Graph endpoints:

- [x]  ```FAIL tests/api_tests.Test0boxGraphAndTotalEndpoints/test_graph_data_(_test_/v2/graph-total-locked_) (122.07s)```

- [x] Zs3server:

- `GetObjects should return 200 all the parameter are correct`
- `PutObjects should return 200 all the parameter are correct`
- `ListObjects should return 200 all the parameter are correct`

**Comment by Hitenjain14** [comment]
ZS3 issue should be fixed by https://github.com/0chain/blobber/pull/1203

**Comment by Kishan-Dhakan** [comment]
Zs3 item closed by https://github.com/0chain/system_test/pull/823 and https://github.com/0chain/blobber/pull/1203
