### ISSUE TITLE
Use underscore in test names.

### ISSUE THREAD

**Issue by Sriep** [0chain/system_test#92]
When you run a test you might get a result like
```
=== Failed
=== FAIL: tests/cli_tests TestUpdateAllocation/Cancel_Allocation_Should_fail_when_blobber_passes_challenges (16.41s)
=== FAIL: tests/cli_tests TestUpdateAllocation (0.00s)
```
 When you find in files in `system_test` for `Cancel_Allocation_Should_fail_when_blobber_passes_challenges` you can't find it. This is because in the code it is `Cancel Allocation Should fail when blobber passes challenges`. The toolchain has converted `space` to `underscore`.

It would be easier for debugging issues if the `t.Run` name in the code matched the name in the output.

Suggest replacing `space` with an `underscore` in `t.Run` name parameter.

**Comment by Kishan-Dhakan** [comment]
@stewartie4 @mohsenno1 thoughts?

**Comment by stewartie4** [comment]
I get your point @Sriep but agree with @Kishan-Dhakan 
The standard in the wild seems to be human readable test names 
I normally just search for the first few words without the underscores, doesn't take much longer than copy + paste 

We use a custom test runner which supports custom formatters, let me see if I can write one that removes the underscores.
It wouldn't be prefect but maybe a bit better than what we have today

**Comment by Kishan-Dhakan** [comment]
Closing this as a stale issue. Please feel free to open a new issue if this is still concerning.
