### ISSUE TITLE
Changes to update allocation request for 0chain PR620

### ISSUE THREAD

**Issue by Sriep** [0chain/system_test#96]
0chain PR620 https://github.com/0chain/0chain/pull/620 and GoSDK https://github.com/0chain/gosdk/pull/288 and zbox   https://github.com/0chain/zboxcli/pull/122  make the following changes to update allocation and new allocation request.

~~1. Allow any user to attempt an update allocation request. Previously GoSDK forced the client and owner to be the same.
2. Extending an allocations expiry date is now allowed by anyone.
3. Reducing the expiry date is no longer permitted.
4. Setting an allocation immutable or changing its size can only be done by the owner.~~

Requirements changed:
1. Allocations cannot have their duration reduced.
2. A new NFT allocation option which can be set in a new allocation request; defaulting to false. It allows anyone to extend the allocation.

**Comment by Sriep** [comment]
https://github.com/0chain/system_test/runs/4092999586?check_suite_focus=true system tested. Failing tests

1. tests/cli_tests.TestFileStats/get_file_stats_before_and_after_download zboxcli_file_stats_test.go:426
2. tests/cli_tests.TestDownload/Download_File_using_Expired_Allocation_Should_Fail zboxcli_download_test.go:917
3. tests/cli_tests.TestUpdateAllocation/Update_Expired_Allocation_Should_Fail  zboxcli_update_allocation_test.go:243
4. tests/cli_tests.TestUpdateAllocation/Finalize_Expired_Allocation_Should_Fail zboxcli_update_allocation_test.go:371
5. tests/cli_tests.TestUpdateAllocation/Cancel_Expired_Allocation_Should_Fail zboxcli_update_allocation_test.go:319
6. tests/cli_tests.TestUpdateAllocation/Update_All_Negative_Parameters_Should_Work zboxcli_update_allocation_test.go:167
7. tests/cli_tests.TestUpdateAllocation/Update_Negative_Expiry_Should_Work zboxcli_update_allocation_test.go:115

**Comment by stewartie4** [comment]
@Sriep 
Looked into this by re-running tests against your images:
https://github.com/0chain/system_test/runs/4097578489?check_suite_focus=true

Download_File_using_Expired_Allocation_Should_Fail -> This test expires an allocation by updating the expiry to be a second in the future.

The other tests failing:
Finalize_Expired_Allocation_Should_Fail (49.83s)
Cancel_Expired_Allocation_Should_Fail (49.87s)
Update_Expired_Allocation_Should_Fail (49.73s)
Update_All_Negative_Parameters_Should_Work (49.77s)
Update_Negative_Expiry_Should_Work (49.84s)
Updates are all failing for some reason

Baseline test run against staging images does not have these issues
https://github.com/0chain/system_test/runs/4097563556?check_suite_focus=true
maybe the test cases are no longer valid or there could be a code issue

**Comment by Sriep** [comment]
After a feature change and rewrite the following failed. Listed here for convenience.

1. - TestUpdateAllocation/Update_All_Negative_Parameters_Should_Work (49.73s)
2. - TestUpdateAllocation/Update_Expired_Allocation_Should_Fail (49.77s)
3. - TestUpdateAllocation/Finalize_Expired_Allocation_Should_Fail (49.76s)
4. - TestUpdateAllocation/Cancel_Expired_Allocation_Should_Fail (49.84s)
5. - TestUpdateAllocation/Update_Negative_Expiry_Should_Work (49.78s)
6. - TestDownload/Download_File_using_Expired_Allocation_Should_Fail (49.05s)

1. Should fail. I cannot see why 2-6 should failed, need to investigate.

**Comment by stewartie4** [comment]
yeah strange, those were failing for me above too

**Comment by SinanEkm** [comment]
Mentioned test cases seem passing in both the local environment and in System Tests.
